Ext.require([
    'Ext.panel.*',
    'Ext.toolbar.*',
    'Ext.button.*',
    'Ext.grid.*',
    'Ext.data.*',
    'Ext.chart.*',
    'Ext.form.*',
    'Ext.container.ButtonGroup',
    'Ext.layout.container.*'
]);
